### ISSUE TITLE
Incompatibility with Carpet

### ISSUE THREAD

**Issue by MagnusRevang** [FalsehoodMC/Fabrication#478] opened 2022-06-16 20:56 UTC
Seems like the same mixin that crashed with Balm also crashes with Carpet Mod. Only happens when Fabrication is enabled, when I remove fabrication, carpet works fine

[latest.log](https://github.com/unascribed/Fabrication/files/8922327/latest.log)

**Comment by SFort** [comment] 2022-06-16 21:20
Duplicate of #470

**Closed as completed by SFort** 2022-06-16 21:20 UTC
Labels: s: Duplicate
