### ISSUE TITLE
A Mixin is failing to inject and I don't know what's causing it.

### ISSUE THREAD

**Issue by yum13241** [FalsehoodMC/Fabrication#558] opened 2022-10-22 18:20 UTC
Version: 1.18.2 of Minecraft
Banned mixins: 
bottled_air=banned (not setting it to banned causes a different crash)

https://gist.github.com/yum13241/aaa3cc970dbe296c2c49ef907f58abb7

**Comment by SFort** [comment] 2022-10-22 18:38
```
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError:
Critical injection failure: Redirector onTexImage(IIIIIIIILjava/nio/IntBuffer;)V in
resolutioncontrol.mixins.json:FramebufferMixin from mod resolutioncontrol
failed injection check, (0/1) succeeded.
Scanned 1 target(s). Using refmap resolution-control-plus-refmap.json
```

**Comment by yum13241** [comment] 2022-10-22 18:39
So resolution control + is the problem?

**Comment by SFort** [comment] 2022-10-22 18:41
yup.
ATM don't even know what it's conflicting with, idealy this would be fixed by resolution control but might be fine todo fabrication side (atm don't even know if it's a conflict with fabrication or any of the other mods you got installed, need to look into)

**Comment by yum13241** [comment] 2022-10-22 18:44
https://gist.github.com/yum13241/6d1c2ac1aa7001c0d030c4c8d90c2299


Disabling RC+ solves the first crash but now I get a new crash.

**Comment by SFort** [comment] 2022-10-22 18:47
idk some mod using artifice / artifice itself. check what's using artifice.

**Comment by SFort** [comment] 2022-10-22 18:58
none of these crashes are caused by fabrication

**Closed as completed by SFort** 2022-10-22 18:58 UTC
Labels: s: Invalid

**Comment by yum13241** [comment] 2022-10-23 04:17
The crazy part is... none of this happens on 1.18.1.

Just need to get the correct versions, remove traverse and its friends, and then the game loads even with bottled air on.

Edit: the author of extra pieces (it uses Artifice) says that the mod doesn't work on 1.18.2. I'll find a replacement.
