### ISSUE TITLE
[1.19.1] Game crashes after starting

### ISSUE THREAD

**Issue by pewblaze** [FalsehoodMC/Fabrication#516] opened 2022-07-30 18:20 UTC
https://gist.github.com/pewblaze/165d03e21cc4e940163555a85888170c

Hi, the game crashes after starting. I also tested it with a new install and this mods:
![grafik](https://user-images.githubusercontent.com/96242065/181936481-36da6267-ee1d-4bbc-990b-02e2fa4c4d78.png)

**Comment by SplendidAlakey** [comment] 2022-07-31 03:22
Duplicate of my issue #515, it happens because of the new chat and social interaction system, ban the features I mentioned and the mod will work.

**Closed as not planned** 2022-07-31 03:42 UTC
Labels: s: Invalid, s: Duplicate

**Comment by pewblaze** [comment] 2022-07-31 09:02
Ah i see! Thank you!
