### ISSUE TITLE
Reference map 'pride-refmap.json' for pride.mixins.json could not be read.

### ISSUE THREAD

**Issue by FewerFlaws** [FalsehoodMC/Fabrication#302] opened 2021-10-11 08:25 UTC
https://gist.github.com/FewerFlaws/d9dd128d76ac158db9b037f70639c690
`Reference map 'pride-refmap.json' for pride.mixins.json could not be read. If this is a development environment you can ignore this message` appears in my logs.

**Comment by Cynosphere** [comment] 2021-10-11 18:55
Non issue. Anything tagged WARN is mostly debugging and can be safely ignored.

**Comment by exaskye** [comment] 2021-10-11 19:05
The cause is PrideLib, a dependency of Fabrication, contains boilerplate for using mixins but does not actually have any mixins.

Cynosphere is right that this is safe to ignore and therefore incredibly low priority.

**Comment by exaskye** [comment] 2021-10-29 01:31
Fixed by Queerbric/pridelib#4

**Closed as completed by exaskye** 2021-10-29 01:31 UTC
Labels: k: Defect, n: Fabric
