### ISSUE TITLE
Obsidian Tears is still incompatible with OptiFine

### ISSUE THREAD

**Issue by DoctorArchives** [FalsehoodMC/Fabrication#84] opened 2021-01-19 19:28 UTC
<details>
<summary>Crash report:</summary>
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 1/19/21 7:25 PM
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_4599.method_22999(class_4599.java:35)
	at net.minecraft.class_4599$$Lambda$4501/637782050.accept(Unknown Source)
	at net.minecraft.class_156.method_654(class_156.java:358)
	at net.minecraft.class_4599.<init>(class_4599.java:13)
	at net.minecraft.class_310.<init>(class_310.java:531)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method construct(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in fabrication.mixins.json:e_mechanics.obsidian_tears.MixinModelLoader failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabrication-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 19 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_4599.method_22999(class_4599.java:35)
	at net.minecraft.class_4599$$Lambda$4501/637782050.accept(Unknown Source)
	at net.minecraft.class_156.method_654(class_156.java:358)
	at net.minecraft.class_4599.<init>(class_4599.java:13)
	at net.minecraft.class_310.<init>(class_310.java:531)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1226202960 bytes (1169 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adabraniummod: Adabranium 1.3.1+1.16.4
		adapaxels: AdaPaxels 1.0.5+1.16.4
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		advancednbttooltip: Advanced NBT Tooltips 1.3.0+build.2-1.16.4
		alaskanativecraft: Alaska Native Craft 1.0.0
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		architectury: Architectury 1.3.80
		artifacts: Artifacts 2.1.0+1.16.4-fabric
		artifice: Artifice 0.13.1+1.16.2-rc1
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autofish: Autofish 0.9.2
		betterf3: BetterF3 1.1.2
		camp_fires_cook_mobs: Camp Fires Cook Mobs 1.1.6+MC1.16.2-1.16.5
		cardinal-components: Cardinal Components API 2.7.10
		cardinal-components-base: Cardinal Components API (base) 2.7.10
		cardinal-components-block: Cardinal Components API (blocks) 2.7.10
		cardinal-components-chunk: Cardinal Components API (chunks) 2.7.10
		cardinal-components-entity: Cardinal Components API (entities) 2.7.10
		cardinal-components-item: Cardinal Components API (items) 2.7.10
		cardinal-components-level: Cardinal Components API (world saves) 2.7.10
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.7.10
		cardinal-components-util: Cardinal Components API (utilities) 2.7.10
		cardinal-components-world: Cardinal Components API (worlds) 2.7.10
		chorus_links: Chorus Links 1.0.0
		cleanview: CleanView 1.16.5-v1-fabric
		cloth-api: Cloth API 1.4.9
		cloth-armor-api-v1: Cloth Armor API v1 1.4.9
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.9
		cloth-common-events-v1: Cloth Common Events v1 1.4.9
		cloth-config2: Cloth Config v4 4.8.3
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
		cloth-scissors-api-v1: Cloth Scissors API v1 1.4.9
		cloth-utils-v1: Cloth Utils v1 1.4.9
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		crowdin-translate: CrowdinTranslate 1.2
		curios: Curios API 0.0.11-1.16.4
		dracomelette: Dracomelette 1.16.5-1
		dual_riders: DualRiders 1.0.5
		dynamicfps: Dynamic FPS 2.0.0
		dynmus: Dynamic Music 1.0.0
		earthtojavamobs: Earth2Java 1.6.1+1.16.4
		economical_villager_trading: Economical Villager Trading 1.0.3+MC1.16.4-1.16.5
		eggtab: Egg Tab 2.1.0+1.16-fabric
		eldritch_mobs: Eldritch Mobs 1.6.5
		enchant_giver: Enchant Giver 1.0.2
		enchantment_lore: EnchantmentLore 1.1.1+MC1.16.1-1.16.5
		fabric: Fabric API 0.29.3+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.1+cbe9176f3a
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.2+8004b36d3a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.5+cbe9176f3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.2+cbe9176f3a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
		fabric-language-kotlin: Fabric Language Kotlin 1.4.21+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
		fabric-models-v0: Fabric Models (v0) 0.2.0+cbe9176f3a
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
		fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: Fabric Particles (v1) 0.2.3+cbe9176f3a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.0+cbe9176f3a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.0+c26373133a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.1+0d4d7e343a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.3+cbe9176f3a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabrication: Fabrication 1.2.11
		fabricloader: Fabric Loader 0.11.1
		fabrictailor: Fabric Tailor 1.4.0-1.16.4
		fallingleaves: Falling Leaves 1.4
		faster-minecarts: Faster Minecarts 1.0.0
		fedora: Fedora 1.1.1-fabric-1.16.4
		fiber: fiber 0.23.0-1
		goldensteak: Goldensteak 1.0.2
		greater_eye: Greater Eye of Ender 1.1.5
		haema: Haema 1.4.1
		harvest_scythes: Harvest Scythes 1.0.8
		heartbond: Heartbond 1.0.0
		hitmarker: HitMarker 1.0a-1.16.2
		homecamp: Home Camp 1.0.3
		hplus: Hopper Plus 1.0.10
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.2.2+1.16.3
		map_atlases: Map Atlases 1.0.0
		mcda: MC Dungeons Armors 0.9.3
		mcdw: MC Dungeons Weapons 2.5.0
		minecraft: Minecraft 1.16.5
		mm: Manningham Mills 2.1
		modmenu: Mod Menu 1.14.13+build.19
		monster-in-the-closet: Monsters in the Closet 1.0.0
		multi_item_lin: Multi Item Lin 1.0.0
		netherite_nugget: Netherite Nugget 1.2.1
		netherite_plus: Netherite Plus Mod 1.3.4-1.16.5
		optifabric: OptiFabric 1.8.16
		org_codehaus_groovy_groovy: groovy 3.0.3
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		oro_config: OroArmor Config -0df99c92b1-1
		overpowered_mending: Overpowered Mending 2.2.2
		patchouli: Patchouli 1.16-40-FABRIC
		peacefulsurface: PeacefulSurface 1.16.5-v1-fabric
		playerabilitylib: Pal 1.2.1
		pling: Pling 1.3.0
		pulverizer_mod: Pulverizer Mod 1.1.1
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		redbits: Red Bits 1.7.0
		repurposed_structures: Repurposed Structures 1.16.4-1.7.4
		roughlyenoughitems: Roughly Enough Items 5.8.10
		roughlyenoughitems-api: REI (API) 5.8.10
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.10
		roughlyenoughitems-runtime: REI (Runtime) 5.8.10
		rpgstats: RPGStats 3.0.6+1.16.4
		ruined_equipment: Ruined Equipment 1.2.2
		satin: Satin 1.4.1
		seamless_loading_screen: Seamless Loading Screen 1.1.0
		shulkerboxtooltip: Shulker Box Tooltip 2.3.4+1.16.4
		simple_backpack: SimpleBackpack 1.0.38
		skinnedlanterns: Skinned Lanterns 1.16.4-1.1.1
		slight-gui-modifications: 'Slight' GUI Modifications 1.6.1
		slime_sling: SlimeSling 1.0.0
		spellbound: Spellbound 1.1.0
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		timechanger: Time Changer 1.0.0
		totemmod: Wither Totems Mod 0.3.2
		trinkets: Trinkets 2.6.7
		truerooms: True Secret Rooms 1.1.2-hotfix
		voyager: Voyager 1.0.0
		worldedit: WorldEdit 7.2.2+fc3c499
		xaerobetterpvp: Better PVP Mod 21.1.0
		xaeroworldmap: Xaero's World Map 1.11.9
	Patchouli open book context: n/a
	Launched Version: fabric-loader-0.11.1-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 460.89, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.16.5_HD_U_G6
	OptiFine Build: 20210117-013236
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 460.89
	OpenGlRenderer: GeForce RTX 2060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.16.5
	OptiFine jar version: OptiFine_1.16.5_HD_U_G6
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:\Users\shafe\AppData\Roaming\.minecraft\.optifine\OptiFine_1.16.5_HD_U_G6\Optifine-mapped.jar
	OptiFabric error: <None>
</details>

**Comment by exaskye** [comment] 2021-01-22 21:01
Workaround: Disable `Mechanics > Obsidian Tears`.

This is the third time I've had this reported after thinking I'd fixed it.

True fix: [Stop using OptiFine, god damn it.](https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754)

**Comment by DoctorArchives** [comment] 2021-01-24 07:51
@unascribed Alright, I removed OptiFabric and Optifine and then turned off Obsidian Tears and later put them back in the mods folder, it seems to be working perfectly now, thanks!

**Comment by DoctorArchives** [comment] 2021-01-24 07:52
You can close the issue.

**Comment by exaskye** [comment] 2021-01-24 07:58
Won't close the issue because the issue isn't fixed.

**Comment by DoctorArchives** [comment] 2021-01-24 20:19
Oh, okay, well, it's temporarily fixed, I guess, so thanks again.

**Comment by exaskye** [comment] 2021-01-24 22:25
Effectively fixed by new mixin robustness.

**Closed as completed by exaskye** 2021-01-24 22:25 UTC
Labels: k: Incompatibility, n: Fabric, n: OptiFine
