### ISSUE TITLE
Fair Infinity

### ISSUE THREAD

**Issue by peow** [FalsehoodMC/Fabrication#694] opened 2024-02-12 21:12 UTC
the Infinity enchantment has some problems, it makes arrows extremely useless to make in large quantities, as happens in every game where there are bows, Mojang tried to fix this by preventing Infinity from being enchanted together with Mending, but this did not make it fair at all and It didn't solve a big problem: the Tipped Arrows are left completely aside because the Infinity enchantment doesn't affect them, and so no one uses them

There are several mods that let the Infinity enchantment work with Mending, and there are some mods that allow Tipped Arrows to be affected by Infinity, but even with these mods, there is still a problem to be solved: the ease of obtaining the Infinity enchantment, and how useful it is, making him indispensable in the bow, how to solve it then?

The answer to this is making a change to the Infinity enchantment, making it work similar to the Unbreakable enchantment, when you shoot an arrow, there is a possibility that the arrow will not be used, and this would work with Tipped Arrows and Spectral Arrows

and this change in the Infinity enchantment already happens in Minecraft Dungeons, where it has 3 levels, at level 1 there is a 16% chance of the arrow not being used, at level 2 there is a 32% chance of the arrow not being used, and at level 3, 48% (https://minecraft.fandom.com/wiki/Minecraft_Dungeons:Infinity)

I believe that these numbers are a little smaller than they should be, I believe that 20/40/60 would be more interesting, and finally, I wanted to highlight that there is a mod that makes this change in the enchantment, however this mod is already dead and is not more updated for new versions of Minecraft Fabric: https://modrinth.com/mod/infinity_fix (on the website the license is marked as LGPL-3.0-only, but inside the fabric.mod file it is marked as MIT)

I believe that this change would fit into the "Balance" category, if you find this suggestion interesting, I ask you to add it to Fabric 1.20.1

**Comment by SFort** [comment] 2024-02-12 21:50
Duplicate of #653
due to lack of time features requests are generally on hold, unless they take minutes to implement.
also this is more complicated that you might think as making it work seamlesly server-side only is not a two minute implementation. (unless i missed something when i did make this feature but shelved it because of jank desyncs)

also most verbose feature request award?

**Closed as completed by SFort** 2024-02-12 21:50 UTC
Labels: s: Duplicate, k: Feature Request

**Comment by peow** [comment] 2024-02-13 16:43
oh, sorry for not remembering to research first, and yes, I know that making mods is very difficult, that's why I mentioned a mod that already has this functionality in the hope that the code from this mod can somehow facilitate implementation

thank you for reading my giant text xd
