### ISSUE TITLE
I had a crash after installing Fabrication on the client and server

### ISSUE THREAD

**Issue by YumatanGames** [FalsehoodMC/Fabrication#498] opened 2022-06-26 04:34 UTC
Client's log: https://gist.github.com/YumatanGames/61fa944a6a6820794fbac019c8eaa438

Server's log: https://gist.github.com/YumatanGames/7c45d7f604f81a9e55ae0feeb2bca23e

**Comment by SFort** [comment] 2022-06-26 08:27
Duplicate of #495

**Closed as not planned** 2022-07-03 09:59 UTC
Labels: s: Duplicate, k: Incompatibility, n: Fabric
