### ISSUE TITLE
Fabrication update compabilitiy issue with Artifacts and Debugify

### ISSUE THREAD

**Issue by Zelioth** [FalsehoodMC/Fabrication#568] opened 2022-11-03 05:46 UTC
Updating Fabrication to the latest release 3.1.2 + 1.19 causes instant crash on startup with Artifacts and Debugify.

downgrading to version 3.1.1 fixes the issue e

**Comment by exaskye** [comment] 2022-11-03 05:48
Likely a duplicate of #566 and is missing information.

**Closed as not planned by exaskye** 2022-11-03 05:48 UTC
Labels: s: Invalid
