### ISSUE TITLE
[Forge 1.16.5] Injection error: Could not find any matching targets

### ISSUE THREAD

**Issue by GAsplund** [FalsehoodMC/Fabrication#360] opened 2021-12-06 19:17 UTC
I'm fully unsure what is causing this. I used to be able to circumvent the issue by running an older version of forge (36.2.2), but other mod updates forced me to update to a newer version of forge, which causes some kind of mod incompatibility. All I could dig out from the log is that's in relation to injection into `method_17410` for the `fullExperienceCost` method.

I am running on the latest published build (`2.2.1-exp1`) but this is happening on older versions as well.
Forge version 36.2.19

debug.log - https://gist.github.com/GAsplund/cb9d23b9c6379f054b284f4ad8b5da04

**Comment by exaskye** [comment] 2021-12-06 19:36
Duplicate of #357

Something about your environment is promoting this soft failure into a hard crash.

Set `full_experience_cost` in `features.ini` to `banned` as a temporary workaround.

**Closed as completed by exaskye** 2021-12-06 19:36 UTC
Labels: s: Duplicate, k: Incompatibility, n: Forge
