### ISSUE TITLE
Giant implementation

### ISSUE THREAD

**Issue by saltyseadoggo** [FalsehoodMC/Fabrication#45] opened 2021-01-08 05:24 UTC
Minecraft: Java Edition and Legacy Console Edition both include an unused Giant mob. You can read about it and its history on [the official Minecraft wiki article](https://minecraft.gamepedia.com/Giant), but, essentially, it is an almost twelve block tall zombie with drastically inflated hit points and damage. It cannot spawn due to not appearing in any biome's spawn lists and needing to meet the impossible spawn condition of a light level over 11 and below 8, and, although it can be spawned with /summon, it has no AI ever since snapshot 14w06a. 18w50a gave the giant AI, sounds and everything needed for it to function as a copy of the zombie that moves twice as fast, but this was scrapped again in 19w05a. Again, the precise details of this implementation of it are on the page above, in the History section.

As a niche/joke option, I would like a tweak that restores the giant to its functional state from 18w50a, and allows it to spawn rarely in the overworld by adding it to biome spawn lists and making its spawn conditions possible to meet. It may need a loot table for rotten flesh drops as well; the wiki doesn't mention whether the snapshot gave it one. Naturally, its size would keep it out of most caves and forested biomes, so it may only appear to ravage empty biomes such as plains or deserts.

As additional features, one could be summoned by the zombie siege event that occurs in villages, and they could be allowed to spawn with armour or an iron shovel or sword with the same chance as zombies, or perhaps a greater chance to spawn with rarer types to reward fighting them.~

**Comment by exaskye** [comment] 2021-01-08 05:36
Oh, I am well aware of the Giant. Its primary issue (and reason for repeated removal) is that the engine is *very bad* at large mobs. As an off-by-default option (not *quite* old enough to qualify for WOINA; maybe Mechanics?) I'll consider it.

**Comment by saltyseadoggo** [comment] 2021-01-08 05:42
Is that so? Can you elaborate on the engine's struggles with large mobs? I am presuming that you mean larger than the Ravager or the Wither, as I have not witnessed them having issues, although I may have missed something obvious, I confess.

I just thought *beeg zombie* could be a fun gag option.~

**Comment by exaskye** [comment] 2021-01-08 06:15
Minecraft's collision code is... not efficient, and the AI code is very, *very* bad at anything with a footprint larger than ~3 blocks. Even Ravagers have (hard to explain) pathfinding errors, and the Wither cheats by not *really* having pathfinding at all; it just kind of vaguely floats and approaches its target.

There is also the issue of overhanging caused by a large mob standing on the edge of a block; it's visible on small mobs too but it's exaggerated on big ones. Minecraft's model and rendering system entirely lacks a solution to that and it'd need a major overhaul to fix it; such an overhaul would also probably change the art style, so it won't happen, but yeah.

On the less technical side, the combat system in Minecraft is already not very good and introducing large mobs with a lot of health just turns it into a huge chore; the epitome of "hit it 'til it falls down".

The only truly *big* thing in Minecraft that works halfway decent is the Ender Dragon; but collision doesn't work right for it (that's why it destroys blocks) and it's actually about a dozen entities glued together.

**Comment by saltyseadoggo** [comment] 2021-01-08 06:37
Okay, these points make sense. I wouldn't blame you for letting this beastie be. It could be a kind of jank joke tweak for those who are interested, but I don't think much of value would be lost without it now that you explain its issues.

**Comment by saltyseadoggo** [comment] 2021-01-08 06:44
Thank you for explaining!~

**Comment by exaskye** [comment] 2021-01-22 20:59
I've received an overwhelming number of feature requests over the week and they are filling up the issue tracker and making it difficult to keep track of what is even going on. I've enabled [Discussions](https://github.com/unascribed/Fabrication/discussions) on the repo as a new location for feature requests. Unfortunately, GitHub has "temporarily" disabled the ability to convert issues to discussions, so I'm closing all feature request issues. However, I'm tracking all the closed issues in a Project board; despite being closed, they're still on my radar on the board. **All new feature requests *must* go to Discussions. Feature requests opened as issues going forward will be closed.**

**Closed as completed by exaskye** 2021-01-22 20:59 UTC
Labels: k: Feature Request
