### ISSUE TITLE
Game crashes when i click create new world or load a world when i have extra.encroaching_emeralds enabled

### ISSUE THREAD

**Issue by gitunown** [FalsehoodMC/Fabrication#388] opened 2021-12-25 01:43 UTC
https://gist.github.com/gitunown/bce59b7db3a389f8881caf1afd3c4bef

**Comment by exaskye** [comment] 2021-12-25 01:45
Duplicate of #373 

This has been fixed but not yet released.

**Closed as completed by exaskye** 2021-12-25 01:45 UTC
Labels: s: Already Fixed, k: Defect, s: Duplicate, n: Fabric
