### ISSUE TITLE
Campfires cook meat drops from killed mobs

### ISSUE THREAD

**Issue by saltyseadoggo** [FalsehoodMC/Fabrication#69] opened 2021-01-16 19:34 UTC
I would like to see a gameplay tweak that makes mobs killed by campfires that drop meat drop cooked meat, as if they were killed by fire damage. However, I do not want the campfires to set things on fire, as the vanilla campfire damage implementation has applications in mob farming, notably in killing witches that would drink potions to become immune to other sources of fire damage.

This is similar to [Camp Fires Cook Mobs](https://gitlab.com/supersaiyansubtlety/camp-fires-cook-mobs), and I suggest this because you've expressed wanting Fabrication/Forgery to be a *one stop shop* for tweaks, but would be without the additional fluff of that mod's Frost Walker changes.

**Comment by K0-RR** [comment] 2021-01-22 10:38
From my bulk feature request.
"Fix fire damage not always giving cooked drops caused by inconsistency with how loot tables check if the mob was on fire. The vanilla mechanic only checks for "damage over time" fire damage and not instant fire damage. This has lead to many edge cases where things like the vanilla Camp Fire block and various fire mechanics in other mods will not cause mobs to drop the correct items"

**Comment by exaskye** [comment] 2021-01-22 20:55
I've received an overwhelming number of feature requests over the week and they are filling up the issue tracker and making it difficult to keep track of what is even going on. I've enabled [Discussions](https://github.com/unascribed/Fabrication/discussions) on the repo as a new location for feature requests. Unfortunately, GitHub has "temporarily" disabled the ability to convert issues to discussions, so I'm closing all feature request issues. However, I'm tracking all the closed issues in a Project board; despite being closed, they're still on my radar on the board. **All new feature requests *must* go to Discussions. Feature requests opened as issues going forward will be closed.**

**Closed as completed by exaskye** 2021-01-22 20:55 UTC
Labels: k: Feature Request
