### ISSUE TITLE
Add support for Mod Menu.

### ISSUE THREAD

**Issue by K0-RR** [FalsehoodMC/Fabrication#17] opened 2020-10-31 12:52 UTC
I would be nice if we could change the config the the Mod Menu.

**Comment by exaskye** [comment] 2020-10-31 13:00
Sort of a dupe of #3; while splitting up that issue I forgot about the mod menu support request. Here's my response about that from there:

-----

> First off, it'd be great if the config could be made ModMenu compatible. As an INI I'm not sure if that's doable?

As far as I know, ModMenu doesn't care about your config format. It just provides a button to open a custom Screen, which can be whatever I like.

I intend to do this, it's just a lot of work compared to making a lot of minor tweaks. (UI design is hard work.)

**Closed as completed** 2020-11-01 11:50 UTC
Labels: k: Feature Request

**Comment by exaskye** [comment] 2020-11-01 11:59
<a href="https://pool.jortage.com/sleepingtown/media_attachments/files/003/531/571/original/a3bd371a57b69c81.mp4">
<img title="Demonstration video" src="https://pool.jortage.com/sleepingtown/media_attachments/files/003/531/571/small/a3bd371a57b69c81.png"/>
</a>

UI design is especially hard work when you're me and you can't just settle for vanilla UI components.
