### ISSUE TITLE
Fabrication and Charm

### ISSUE THREAD

**Issue by DadoIrie** [FalsehoodMC/Fabrication#506] opened 2022-07-16 08:52 UTC
no idea what it means or does (something about a amethyst dupe fix), but I thought reporting this as it sounds game breaking and no idea if this fix is still needed or if it is fixed by charm itself  by now

here is the uploaded log (note that only fabric api, charm & fabrication are loaded and the other mods are disabled)
[https://mclo.gs/oHkTBNI](https://mclo.gs/oHkTBNI)

EDIT: for now I've banned that setting, but still interested if this needs a fix

**Comment by SFort** [comment] 2022-07-16 09:51
Duplicate of #495

so it's been fixed just not released yet

> "fixed by charm itself by now" 

Charm#639 was closed with no comment.
to my knowladge charm has still made no changes to fix the dupe

**Comment by exaskye** [comment] 2022-07-16 16:04
Just checked the current Charm code; they have not fixed the dupe.

I'll release a pre6 in a bit with the fix.

**Closed as completed by exaskye** 2022-07-16 16:04 UTC
Labels: k: Incompatibility, n: Fabric
