### ISSUE TITLE
Game crashed at start with new version of forgery

### ISSUE THREAD

**Issue by Tw1L1ght12** [FalsehoodMC/Fabrication#569] opened 2022-11-03 10:18 UTC
[https://gist.github.com/Tw1L1ght12/93d26309bac3b951f3ae3107101fe8c8](url)

All works fine in previous version

**Comment by SFort** [comment] 2022-11-03 10:43
Duplicate of #566 
should be fixed in 3.1.3

**Closed as completed by SFort** 2022-11-03 10:43 UTC
Labels: k: Incompatibility, n: Forge
